# -*- coding: utf-8 -*-
"""House Price Data Analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ird3QiJv8biWyZ2av0UHClEHBsqZYvc
"""

from google.colab import files
from IPython.display import Image

Image('/content/hn3k_a1c6_141031.jpg',width=725)

"""Import Libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score,mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.svm import SVR
from sklearn.linear_model import Lasso, Ridge
from lightgbm import LGBMRegressor
import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score

"""Import Datasets"""

df=pd.read_csv('/content/Housing.csv')

df.head()

df.info()

df.shape

df.describe()

df.isnull().sum()

df.duplicated().sum()

"""Data Visualization 📊📈📉"""

sns.barplot(x=df['airconditioning'],y=df['bedrooms'],hue=df["furnishingstatus"])

sns.barplot(x=df['hotwaterheating'],y=df['bathrooms'],hue=df["furnishingstatus"])

fig, axs = plt.subplots(2,3, figsize = (10,5))
plt1 = sns.boxplot(df['price'], ax = axs[0,0])
plt2 = sns.boxplot(df['area'], ax = axs[0,1])
plt3 = sns.boxplot(df['bedrooms'], ax = axs[0,2])
plt1 = sns.boxplot(df['bathrooms'], ax = axs[1,0])
plt2 = sns.boxplot(df['stories'], ax = axs[1,1])
plt3 = sns.boxplot(df['parking'], ax = axs[1,2])

Q1 = df.price.quantile(0.25)
Q3 = df.price.quantile(0.75)
IQR = Q3 - Q1
df = df[(df.price >= Q1 - 1.5*IQR) & (df.price <= Q3 + 1.5*IQR)]

plt.boxplot(df.price)

Q1 = df.area.quantile(0.25)
Q3 = df.area.quantile(0.75)
IQR = Q3 - Q1
df = df[(df.area >= Q1 - 1.5*IQR) & (df.area <= Q3 + 1.5*IQR)]
plt.boxplot(df.area)

sns.boxplot(x = 'furnishingstatus', y = 'price', hue = 'airconditioning', data = df)

sns.distplot(df["bathrooms"],hist=False)
sns.distplot(df["bedrooms"],hist=False)

sns.scatterplot(y=df['price'],x=df['area'],hue=df['furnishingstatus'])

sns.pairplot(df,hue="furnishingstatus")